### ISSUE TITLE
Automatic BindingContext not working when creating page in code behind.

### ISSUE THREAD

**Issue by SamJames101** [PrismLibrary/Prism.Maui#111]
Hello,

I have created a page in the code behind using :

MyPage myPage = new MyPage();
or
(MyPage)Activator.CreateInstance(typeof(MyPage));

When I check the binding context it is null. 

I haven't added anything into the XAML as I know the AutowireViewModel is done by default now. 
The binding context also successfully worked when I set the same page as a view inside of the tabbed page:

    <NavigationPage Title="title">
        <x:Arguments>
            <Views:MyPage/>
        </x:Arguments>
    </NavigationPage>

BindingContext also works when I navigate to the same page using navigateAsync.

**Comment by dansiegel** [comment]
you are correct the BindingContext would indeed be null... You should be creating the Navigation Stack with the NavigationService. The behavior of Autowire has changed from Forms to what it should have been all along which is that Autowire is not triggered by setting a BindableProperty but rather that it is triggered at the correct point by the NavigationService.

you can replicate this like:
```cs
navService.NavigateAsync("NavigationPage/MyPage");

// OR with a FlyoutPage
navService.NavigateAsync("MyFlyoutPage/NavigationPage/MyPage");
```

**Comment by mnxamdev** [comment]
If Autowire no longer works as it used to, what is the recommendation for applying a ViewModel to the FlyoutPage.Flyout (menu basically) when using Prism.Maui? We currently have a ContentPage in the FlyoutPage.Flyout with a ViewModel that used to work with Autowire but now nothing is binding in that view. Thanks!

**Comment by dansiegel** [comment]
So the guidance hasn't ever changed... You should never have a ViewModel for the Flyout... it should be for the FlyoutPage itself. Now that being said the support for Regions does change things so that you could have something like:
```xml
<FlyoutPage>
  <FlyoutPage.Flyout>
    <ContentPage Title="Menu">
      <ContentView prism:RegionManager.Name="Menu" />
    </ContentPage>
  </FlyoutPage.Flyout>
</FlyoutPage>
```

With Prism.Maui this would then let you have a View/ViewModel that doesn't know it's the child of the FlyoutPage.Flyout and you should get the correct instance of the Navigation Service.

**Comment by mnxamdev** [comment]
Thanks @dansiegel for your prompt reply, I completely agree with your statement with where the ViewModel belongs. However, as you know, in this industry you end up going to jobs where you inherit code and sometimes it's great code and sometimes it's terrible. This code base has a ton of custom master/detail created in code with customer navigation (instead of using OOB Prism Navigation) with using PushAsync for the detail pages. So right now because the Autowire doesn't work as it used to, any page seems to not bind properly to their ViewModels even though the ViewModels are firing up as a result of using Navigation and Views are shown in the Detail area. 
```
 prism.OnAppStart(navigationService => navigationService.CreateBuilder()
                        .AddSegment<MainMasterDetailPage>()
                        .AddSegment<MasterDetailContentNavigationPage>()
                        .AddSegment<MyContentPage>()
                        .NavigateAsync(HandleNavigationError));
```

This transition to MAUI has not been easy. Higher ups are chomping at the bit to rewrite this thing using popular JS based framework and this poor transition to MAUI might just add fuel to that fire. I'll give your recommendation a go and hope things become easier in this transition to MAUI. Thanks for all your work and guidance!

**Comment by dansiegel** [comment]
Remember [Enterprise Support](https://avantipoint.com/developer/support?utm_source=github&utm_medium=issue111) is an option.
